[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.27"
optimizer = true
optimizer_runs = 100_000
viaIR = true

[rpc_endpoints]
etherlink="https://node.mainnet.etherlink.com"
hyperevm="https://rpc.hyperlend.finance"

[etherscan]
etherlink={ key = "NO_KEY", chain = 42793, url= "https://explorer.etherlink.com/api/" }
